### ISSUE TITLE
Build Image and own logo

### ISSUE THREAD

**Issue by neoaminoglycoside** [TOLDOTECHNIK/buildroot-webkit#11]
Hello, can you help us, not for free. We can`t build src by ourselfs, can you give us VmWare Virtual Machine file, or OVA which we can use for building it via our CI? And We need other logo and cyryllic fonts.
Please help us, we waiting for cost reply.

**Comment by TOLDOTECHNIK** [comment]
Please check your email account. We wrote you a message.

**Comment by neoaminoglycoside** [comment]
neoaminoglycoside {at} gmail.com - nothing there. ;(

**Comment by neoaminoglycoside** [comment]
Thanks
