### ISSUE TITLE
Overscan settings

### ISSUE THREAD

**Issue by davidenke** [TOLDOTECHNIK/buildroot-webkit#15]
Is it possible to configure over-/underscan settings with an prebuild image?
Are there settings to be set in the `config.txt` or elsewhere?

**Comment by TOLDOTECHNIK** [comment]
This should work out of the box. Please refer to: https://www.raspberrypi.org/documentation/configuration/config-txt/

**Comment by davidenke** [comment]
@TOLDOTECHNIK you're right it works as expected and is considered in the boot screen. But the webkit window ignores this. Is this ignored by the x server or does it require other settings?

**Comment by davidenke** [comment]
The option `overscan_scale` did the trick, but as [mentioned in the documentation](https://www.raspberrypi.org/documentation/configuration/config-txt/video.md) it is not recommended as it requires the gpu to align non framebuffer alignments...

**Comment by TOLDOTECHNIK** [comment]
Ok, thanks for finding this out. Unfortunately we do not have any good solution for this.
