### ISSUE TITLE
Fixing missing terminal info

### ISSUE THREAD

**Issue by hlev** [TOLDOTECHNIK/buildroot-webkit#2]
https://github.com/TOLDOTECHNIK/buildroot-webkit#osx-terminal-error-when-using-nano

This issue is caused by missing [Terminfo](https://en.wikipedia.org/wiki/Terminfo) data from the build.
The `ncurses` package installs a couple of them, but not for all the common terminal emulators. See https://github.com/WebPlatformForEmbedded/buildroot/blob/b67092fc5c92b3c09ad845296b3dc2734b91a66c/package/ncurses/ncurses.mk#L52

An easy fix, without introducing a new package or patching `ncurses.mk` is to create a filesystem overlay for `/usr/share/terminfo` and place the files such as `/usr/share/terminfo/x/xterm-256color` there. The files are architecture independent binaries, they can be taken from any Linux distribution or machine, or from here http://invisible-island.net/ncurses/ncurses.faq.html#which_terminfo

**Comment by TOLDOTECHNIK** [comment]
This is a much better approach than overwriting the TERM variable. We created the `/usr/share/terminfo/x/` overlay and put in the `xterm-256color` terminfo database file.
`/root/.profile` is removed now.
So, if there is some incompatibility in the future we easily can add other terminfo database files.
Thanks.

See: c39aedca0622210325c2c3989368bbaab612a580
