### ISSUE TITLE
Is it possible to add node libs in the buildroot?

### ISSUE THREAD

**Issue by danielmorena** [TOLDOTECHNIK/buildroot-webkit#22]
I'm interested in add node GPIO libs, and omxplayer via dbus control. Is it possible extending this script? how i include this, is there a documetation?

**Comment by danielmorena** [comment]
Also, is it possible to include a pre-configured terminal command? I want to switch between read-only and write-only fs modes using a bash script

**Comment by TOLDOTECHNIK** [comment]
Please refer to https://github.com/TOLDOTECHNIK/buildroot-webkit/issues/9#issuecomment-486373284 for adding node.js modules.

omxplayer is already included in the prebuilt images.

**Comment by TOLDOTECHNIK** [comment]
You can make the `/dev/root` read-only by editing `/etc/fstab`.
There's also an option in `make menuconfig` (`System configuration` -> `remount root filesystem read-write during boot`)

**Comment by danielmorena** [comment]
excellent, i will try the receipt for the build root. Let me ask a final question, is it possible to create the image with a custom software? I mean to create an image with my app pre packed? where do i place the files?

**Comment by TOLDOTECHNIK** [comment]
Best way to store custom binary files is in: `./board/toldotechnik_rpi/rootfs-overlay/usr/local/bin/`

**Comment by TOLDOTECHNIK** [comment]
Have you already made progress?

**Comment by danielmorena** [comment]
yes! thanks for the support!
