### ISSUE TITLE
How to disable the startup logo

### ISSUE THREAD

**Issue by sahil-siwatch** [TOLDOTECHNIK/buildroot-webkit#23]
Hello team TOLDOTECHNIK. Great job in making this tutorial. I want to disable the logo that is shown on the boot i.e your company's logo. Can you guide me how I can do it ? I am using the image for the RPi3B+. 
Thanks and regards

**Comment by TOLDOTECHNIK** [comment]
You can delete the `/usr/bin/psplash` binary.
