### ISSUE TITLE
not connecting to the wifi network

### ISSUE THREAD

**Issue by sahil-siwatch** [TOLDOTECHNIK/buildroot-webkit#24]
Hello. I am using RPi3B+ image as given by you guys. I have filled my wifi credentials in the wpa_supplicant.conf file but it doesn't seem to be connecting. I also tried adding the country=IN and keeping the network open but it doesn't work. Here is screenshot of my wpa file.
![image](https://user-images.githubusercontent.com/53403558/106705104-4d2ae280-6613-11eb-9a3f-780bbb0f2428.png)

**Comment by TOLDOTECHNIK** [comment]
Try to remove the quotes (ssid=POCO)
Ensure that the `wpa_supplicant.conf` file gets deleted on the `/boot` partition after first boot.

**Comment by sahil-siwatch** [comment]
> Try to remove the quotes (ssid=POCO)
> Ensure that the `wpa_supplicant.conf` file gets deleted on the `/boot` partition after first boot.
Do I do this step before the first boot ?
I am using the prebuild images provided by you.

**Comment by TOLDOTECHNIK** [comment]
1. Save the `wpa_supplicant.conf` to the boot partition.
2. Boot up your RPi
3. Check, if the config file was deleted from `/boot`

**Comment by sahil-siwatch** [comment]
> 1. Save the `wpa_supplicant.conf` to the boot partition.
> 2. Boot up your RPi
> 3. Check, if the config file was deleted from `/boot`

No. It wasn't deleted. It was at the place where it was in the beginning. I edited the file in my laptop using sd card reader. I hope i am doing it correctly

**Comment by TOLDOTECHNIK** [comment]
Ok, then maybe you have a wrong file name. Check if your text editor automatically adds a `.txt` filename extension.

**Comment by sahil-siwatch** [comment]
> Ok, then maybe you have a wrong file name. Check if your text editor automatically adds a `.txt` filename extension.

![image](https://user-images.githubusercontent.com/53403558/106722046-7c4d4e00-662b-11eb-8033-8e4a1b855d46.png)
I don't think that it is adding .txt,

**Comment by TOLDOTECHNIK** [comment]
Can you please post the file's content?

**Comment by sahil-siwatch** [comment]
> Can you please post the file's content?

ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=IN

network={
  ssid=POCO
  psk=""
}

**Comment by TOLDOTECHNIK** [comment]
You still have quotes in you config (`psk=""`). Try `psk=`

**Comment by sahil-siwatch** [comment]
okay. I tried removing them as well. It doesn't work :(

**Comment by TOLDOTECHNIK** [comment]
Sad. Try flashing the hole system again and take the sample config from `/boot`.

**Comment by sahil-siwatch** [comment]
the procedure given here will work for rpi3b+. right ??

**Comment by TOLDOTECHNIK** [comment]
Yes.

**Comment by sahil-siwatch** [comment]
okay i will build it on my ubuntuwith multiple cores. fingers crossed.

**Comment by sahil-siwatch** [comment]
> okay i will build it on my ubuntuwith multiple cores. fingers crossed.

Hello. I am able to run the image now. Thanks a lot for the help. Can I change the browser now i.e from WPE to any other browser ? I am using the pre-built image by you guys. Can I install new packages and other apps ??

**Comment by sahil-siwatch** [comment]
> Yes.

Hello. I am able to run the image now. Thanks a lot for the help. Can I change the browser now i.e from WPE to any other browser ? I am using the pre-built image by you guys. Can I install new packages and other apps ??

**Comment by TOLDOTECHNIK** [comment]
There is no other browser supported. Before compile you can run `make menuconfig` to choose other applications.

**Comment by sahil-siwatch** [comment]
> There is no other browser supported. Before compile you can run `make menuconfig` to choose other applications.

So there is no change I can make if I am using your prebuilt image ? I tried doing SSH but I think busybox is not installed so I can't see anything except the root thing.

**Comment by TOLDOTECHNIK** [comment]
conversation gets off topic...
