### ISSUE TITLE
error while building

### ISSUE THREAD

**Issue by sahil-siwatch** [TOLDOTECHNIK/buildroot-webkit#26]
Hello. I encountered some error while building the image for my rpi3b+. I am using Ubuntu 18.04.5LTS on VirtualBox to build the image. I followed the instructions as described in the documentation. Here is the screenshot of the error message. Can you suggest what might be causing this error ?? 
![image](https://user-images.githubusercontent.com/53403558/106845927-f0423180-66d1-11eb-81ec-6db8b236af38.png)

**Comment by TOLDOTECHNIK** [comment]
Building is supported for Ubuntu 16.04 only for now. Please see https://github.com/TOLDOTECHNIK/buildroot-webkit#prerequisites-ubuntu-1604

**Comment by sahil-siwatch** [comment]
I got the build success using Ubuntu 20.04 and 18.04 both. Just updated the e2fsprogs version and it worked.

**Comment by TOLDOTECHNIK** [comment]
Ok, very good. Thanks.
