### ISSUE TITLE
How to enable touch display

### ISSUE THREAD

**Issue by sahil-siwatch** [TOLDOTECHNIK/buildroot-webkit#27]
hello. I have 5 inch touch screen display for rpi 3b+. https://robu.in/product/5-inch-touch-screen-hdmi-interface-display-module-tft-lcd-800x480-raspberry-pi-2-model-b-touch-pen/?gclid=Cj0KCQiAyJOBBhDCARIsAJG2h5eXf4K4tWBoQ1Q2Y2B9ikgrrpC_3CLkp7SBnB5iyif-6HcWIMHjPgkaAr0AEALw_wcB

How do I enable the touch input ?

**Comment by TOLDOTECHNIK** [comment]
You need to setup a special driver for the touch screen located here: https://github.com/goodtft/LCD-show
Unfortunately we cannot give you more support.

**Comment by sahil-siwatch** [comment]
Okay. Can't you guide me how can I setup third party softwares in your image that I built ??

**Comment by TOLDOTECHNIK** [comment]
Sorry, we cannot provide any further support.
