### ISSUE TITLE
Another boot splash logo

### ISSUE THREAD

**Issue by MaximMikulich** [TOLDOTECHNIK/buildroot-webkit#3]
Hello!) I want another boot splash logo in a prebuilt image...

**Comment by TOLDOTECHNIK** [comment]
Hi,
Thanks for your request. We have to charge 50$ for this service. It takes more than an hour to convert the logo, create psplash patches and create the sdcard.img files.
You will get all the patches and Raspberry Pi Zero/W and 3 B SD card images.
Please contact us by e-mail at info[-|at|-]toldotechnik.li
Regards

**Comment by TOLDOTECHNIK** [comment]
Thanks. Please find your custom binary attached. Move it to `/usr/bin/psplash`
Make sure to have it executable `chmod +x /usr/bin/psplash`
[psplash.zip](https://github.com/TOLDOTECHNIK/buildroot-webkit/files/2723013/psplash.zip)
