### ISSUE TITLE
Utility of S20urandom ?

### ISSUE THREAD

**Issue by NPellet** [TOLDOTECHNIK/buildroot-webkit#33]
I'm adjusting the init scripts to work with systemd and I was wondering about the relevance of S20urandom.
I understand what the script does, I'm just not sure why it was included (doesn't seem documented) ?

Thanks ;)

**Comment by TOLDOTECHNIK** [comment]
Please note that we cannot provide support on this topic. You may get the right answer in the [Buildroot mailing list](https://buildroot.org/support.html).
