### ISSUE TITLE
Web inspector encountered an internal error

### ISSUE THREAD

**Issue by TheLaGmAn** [TOLDOTECHNIK/buildroot-webkit#34]
Im testing this build (actually the release image) in a RPI3.
When using the legacy inspector (http) i always get this errors 24/7 on almost every action on it, making it unusable.
Is this not functional with toldotechnik?
Also, there is no way to enable the not-legacy web inspector? it opens the port but midori cant connect to it, doesnt show anything to inspect

**Comment by TOLDOTECHNIK** [comment]
Hi, we do not understand your question. A so called "inspector" is not supported.

**Comment by TheLaGmAn** [comment]
i meant this part as described in the readme
-------------
You can call the web inspector from an external client browser (tested with Chrome and Safari, not working with Firefox). http://rpi0.local:9998 or http://rpi3.local:9998

If you want do disable it, you can comment out the export WEBKIT_LEGACY_INSPECTOR_SERVER=0.0.0.0:9998 line in /usr/bin/wpe
-------------
Accessing http://x.x.x.x:9998 throws errors 24/7 "web inspector encountered an error", making the inspector unusable, and if i enable 
WEBKIT_INSPECTOR_SERVER=0.0.0.0:9998 (the one that should be used with midrori as inspector://x.x.x.x:9998 it does not find anything to inspect

**Comment by TOLDOTECHNIK** [comment]
You need to use Chrome or Safari.

**Comment by TheLaGmAn** [comment]
Yea, i did, on chrome it does not show anything inside the tabs, thats why i moved into firefox which worked better considering how it works on chrome, maybe it doesnt work anymore with the current chrome version.
Do you know if there is a way to enable the not-legacy version? WEBKIT_INSPECTOR_SERVER

**Comment by TOLDOTECHNIK** [comment]
It's just working on our machines:
<img width="683" alt="grafik" src="https://user-images.githubusercontent.com/6407553/127731122-1bef2ad6-1321-4d1d-a87f-f0b37e31bfcd.png">

Can you please provide more information?

**Comment by TOLDOTECHNIK** [comment]
Did you have success on this?

**Comment by TheLaGmAn** [comment]
only got it to work on edge, FF and chrome does not work and the non legacy method does not work either

**Comment by TOLDOTECHNIK** [comment]
Ok, good news, thanks. Closing for now.
