### ISSUE TITLE
Greek language support

### ISSUE THREAD

**Issue by ligantx** [TOLDOTECHNIK/buildroot-webkit#37]
I try to load a website that is in Greek. But, instead of the greek letters, i see squares. Can it be fixed?

**Comment by TOLDOTECHNIK** [comment]
Can you please provide the URL you want to load?

**Comment by TOLDOTECHNIK** [comment]
You can send it to our company's info email address. Does your html has some encoding meta declaration in the head section (`<meta charset="utf-8"/>`)?

**Comment by ligantx** [comment]
email sent
and no...there is no `utf-8` declaration

**Comment by TOLDOTECHNIK** [comment]
You have the declaration already in the html document: `<META http-equiv="Content-Type" content="text/html; charset=utf-8">` But we did not get the page displayed correctly. This probably have something to do with the webkit browser. We cannot fix it for now.

**Comment by ligantx** [comment]
I see..thank you very much :)
