### ISSUE TITLE
Change the boot screen

### ISSUE THREAD

**Issue by tomkruk** [TOLDOTECHNIK/buildroot-webkit#38]
Is there some way to change or make completely blank the boot screen?

**Comment by TOLDOTECHNIK** [comment]
We did not test it, but you can try to remove the `/usr/bin/psplash` program.

**Comment by tomkruk** [comment]
This DOES work. Thank You. However I can see now that it can be an issue since the black screen can be misunderstood for things not working or being connected. 

Is there a way to change the image into another? Or does the whole thing need to be reassembled?

I am running a small media company where we are trying to have some digital signage. I would ideally want to put a logo and my contact information (in the image), that would be ideal. 

I do not mean to give you guys work but is there a way you can help me out? I am happy to pay for this assistance or advice.

**Comment by TOLDOTECHNIK** [comment]
Please refer to  #3
