### ISSUE TITLE
i want NGINX/PHP image for "RPi0 w" please

### ISSUE THREAD

**Issue by Rdivxe** [TOLDOTECHNIK/buildroot-webkit#41]
i want NGINX/PHP image for "RPi0 w" please
[https://github.com/TOLDOTECHNIK/buildroot-webkit/issues/13#issuecomment-529283054](url)
This does not work with Rasperby 0w. I want to run it on it because the version did not work because it is for Rasperby 3. If you please, please provide a NGINX/PHP version and I will be thankful to you. We will work on an achievement that will be cooperation and you will like it after working on it.

**Comment by TOLDOTECHNIK** [comment]
We'll see if we can achieve that without a lot of effort.

**Comment by Rdivxe** [comment]
@TOLDOTECHNIK Wait for the img php/nginx rpi0w file. Thank you for the help. I hope to work on it as soon as possible.

**Comment by TOLDOTECHNIK** [comment]
We have noticed that we have already provided a detailed setup guide. Please do the following:
Go through all the steps described [here](https://github.com/TOLDOTECHNIK/buildroot-webkit#how-to-build-it-manually). Select the configuration for the RPi0 `make toldotechnik_rpi0_wpe_defconfig`. Before compiling the image follow the steps described [here](https://github.com/TOLDOTECHNIK/buildroot-webkit/issues/13#issuecomment-529283054).

**Comment by Rdivxe** [comment]
@TOLDOTECHNIK These steps are difficult, I can't do it, how do I type make, where do I do it and what kind of operating system is required

**Comment by TOLDOTECHNIK** [comment]
You need a linux based system. Preferably Ubuntu 16.04, because we can guarantee it works.
On a 2.3 GHz Quad-Core Intel Core i5 the build process takes about 2-3 hours.

Don't know if buildroot compilation tasks work on the Raspberry OS. If it does, the build process will take forever.

**Comment by Rdivxe** [comment]
@TOLDOTECHNIK I will give you $3 to make a copy of rpi0w php nginx I will be grateful to you because my capabilities do not allow you to separate me Mr Toldo please help me and make img php nginx file

**Comment by TOLDOTECHNIK** [comment]
Your colleague has already contacted us as well. We have sent him our conditions for commercial use. We are closing the issue because it is no longer relevant for this project.
