### ISSUE TITLE
Magic Mirror

### ISSUE THREAD

**Issue by momochihammer** [TOLDOTECHNIK/buildroot-webkit#42]
Hi - Sorry for the newbie question, but can Magic Mirror for Raspberry Pi be installed on this? I like the lightweight of this since I'm running a Pi zero w.

**Comment by TOLDOTECHNIK** [comment]
Magic Mirror is encapsulated in Electron. For it to run, an X11 server is required. This is not part of our system.

**Comment by momochihammer** [comment]
Thanks for answering so quickly. I really appreciate it.

**Comment by TOLDOTECHNIK** [comment]
We did a little research on the Magic Mirror application. Here's what you can do:

- Run the Magic Mirror in server mode on a host device (https://docs.magicmirror.builders/getting-started/installation.html#manual-installation)
- Point your Raspberry Pi to the host (https://github.com/TOLDOTECHNIK/buildroot-webkit#url-for-the-browser)

**Comment by momochihammer** [comment]
Thanks for doing the extra research for this. I hope this didn't take too much of your time. Will try to see if I can use a host device for the MM.  Thanks again for all your help.
