### ISSUE TITLE
Browser refresh

### ISSUE THREAD

**Issue by burnydoom** [TOLDOTECHNIK/buildroot-webkit#45]
First of all: Thank you for your great work!

How can I set the browser to "F5" in a defined interval?

**Comment by TOLDOTECHNIK** [comment]
Maybe this can help you any further: https://forums.raspberrypi.com/viewtopic.php?t=178206

**Comment by burnydoom** [comment]
Thank you very much. To add the meta information into the index.html worked like a charm!
