### ISSUE TITLE
Custom Splash Image.

### ISSUE THREAD

**Issue by Surebob** [TOLDOTECHNIK/buildroot-webkit#48]
Hello, can you provide me custom boot splash image files for the psplash folder so i can use it in my custom builds? or Walk me through how to use psplash to change the image myself, thank you!

**Comment by TOLDOTECHNIK** [comment]
We can not give you instructions on how to replace the psplash logo. For more information please refer to https://github.com/TOLDOTECHNIK/buildroot-webkit/issues/3
