### ISSUE TITLE
GPIO LCD Driver Support

### ISSUE THREAD

**Issue by jttps** [TOLDOTECHNIK/buildroot-webkit#49]
Hello, would it be possible to install drivers for GPIO hat displays?
I'm trying to install the [LED-show](https://github.com/goodtft/LCD-show) driver for my [3.5" Touch LCD](https://wiki.geekworm.com/3.5_inch_LCD_A) by Geekworm.

**Comment by TOLDOTECHNIK** [comment]
We cannot answer your question. Please contact the manufacturer of the parts.

**Comment by jttps** [comment]
"contact the manufacturer of the parts." Unrelated to the question asked, anyone else that is in a similar situation I will upload a forked solution soon.
