### ISSUE TITLE
RPI Zero 2W Support

### ISSUE THREAD

**Issue by dharmeshmp** [TOLDOTECHNIK/buildroot-webkit#50]
Could you make rpi zero 2w image or provide config for building it)
Thanks

**Comment by TOLDOTECHNIK** [comment]
This needs a lot of effort again because our image is based on an older buildroot branch. So for now we cannot provide any updates/documentation.

**Comment by dharmeshmp** [comment]
Hi @TOLDOTECHNIK 

Thanks for the replay.
