### ISSUE TITLE
Cannot deactivate wifi and activate ethernet

### ISSUE THREAD

**Issue by robandrose** [TOLDOTECHNIK/buildroot-webkit#6]
I am unable to activate the eth0 connection by uncommenting eth0-settings as described in the readme. Would you mind writing a more elaborate description on how to enable a wired network setup? Thanks!

**Comment by TOLDOTECHNIK** [comment]
You're right, uncommenting the whole eth0 section doesn't work. That's because the `/etc/network/nfs_check` does not exist. Please try the following: <img width="680" alt="interfaces" src="https://user-images.githubusercontent.com/6407553/52570253-3a5de880-2e13-11e9-9d48-669e8a351060.png">

**Comment by TOLDOTECHNIK** [comment]
Did you solve your issue?

**Comment by TOLDOTECHNIK** [comment]
Closing, due to no response.

**Comment by robandrose** [comment]
Yes, it did perfectly, thanks a lot.
