### ISSUE TITLE
Pi zero w portrait orientation. Latest disk image

### ISSUE THREAD

**Issue by magnip** [TOLDOTECHNIK/buildroot-webkit#7]
Very bad performance when screen set to display rotate-1
Using as Dakboard, images served from there site.  Tested with full Raspbian and stretch light both work as they should in portrait

**Comment by TOLDOTECHNIK** [comment]
Thank you for your input. Please keep on going with Raspbian.

**Comment by TOLDOTECHNIK** [comment]
Please have a look at this: https://github.com/raspberrypi/firmware/issues/403#issuecomment-86962019
We don't know how the Raspberry Pi Foundation managed to get it run fast in rotation mode.
